# Generated by Django 5.2 on 2025-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_member_fax_alter_member_is_has_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_has_insurance',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='private_practice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
