# Generated by Django 5.2 on 2025-04-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0003_alter_member_email_alter_member_is_has_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_has_insurance',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_of_groups',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='private_practice',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ttd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
