# Generated by Django 5.2 on 2025-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0005_remove_result_name_result_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_has_insurance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_of_groups',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='private_practice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
