# Generated by Django 5.2 on 2025-04-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0010_alter_member_is_has_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_has_insurance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_update',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_of_groups',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='private_practice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='ttd',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
