# Generated by Django 5.2 on 2025-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0012_agency_agencyresult_member_admit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='volunteer_service_history',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
