# Generated by Django 5.2 on 2025-04-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0013_alter_member_volunteer_service_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='firm_or_employer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='has_ever_was_as_judge',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='languages_other_than_english',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='office_type_and_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='practice_areas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
