# Generated by Django 5.2 on 2025-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0014_member_firm_or_employer_member_has_ever_was_as_judge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='objects_to_rent',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='objects_to_sell',
        ),
        migrations.AddField(
            model_name='agency',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agencyresult',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
