# Generated by Django 5.2 on 2025-04-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0015_remove_agency_objects_to_rent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='link',
            new_name='logo',
        ),
    ]
