# Generated by Django 5.2 on 2025-04-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0016_rename_link_agency_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='AgencyResult',
        ),
    ]
