# Generated by Django 5.2 on 2025-04-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0018_alter_member_eligible_to_practice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='firm_or_employer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='languages_other_than_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='license_status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_of_groups',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='office_type_and_size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='practice_areas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='private_practice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
